### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by FosshimotoKovacs** [Every0ne/MozJPEG-GUI#1]
First of all, thanks for making the GUI. Not really an issue but can you make it so that I can run it in a command line in windows. Also can you make it possible for us to manually change the naming format instead of the current naming option.

**Comment by Every0ne** [comment]
You realize this is just a Graphical User Interface for a **command line tool**, right? As for the naming format - it might be worth reconsidering, but I'm making no promises.
